swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions/current-month:
    get:
      tags:
        - Transactions Module
      summary: Get Current Month Transactions
      description: API for fetching all transactions for the current month.
      security:
        - Bearer: []
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      responses:
        '200':
          description: Current month transactions retrieved successfully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid request
        '500':
          description: Internal Server Error

  /user/transactions/{transactionId}:
    get:
      tags:
        - Transactions Module
      summary: Get Transaction Details
      description: API for fetching details of a specific transaction.
      security:
        - Bearer: []
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          required: true
          type: integer
          description: Unique ID of the transaction
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request. Transaction ID must be an integer and larger than 0.
        '500':
          description: Internal Server Error
    put:
      tags:
        - Transactions Module
      summary: Update Transaction
      description: API for updating details of a specific transaction. "Pencil allows user to edit to a Select Dropdown" for category selection and "Pencil allows user to add note via text input" for adding notes.
      security:
        - Bearer: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          required: true
          type: integer
          description: Unique ID of the transaction
        - in: body
          name: body
          required: true
          description: Fields for updating a transaction
          schema:
            type: object
            properties:
              category:
                type: string
                description: New category of the transaction
              notes:
                type: string
                description: Additional notes for the transaction
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid request parameters
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transactions:
    type: object
    properties:
      transactionId:
        type: integer
        format: int64
      date:
        type: string
        format: date-time
      description:
        type: string
      amount:
        type: number
      currency:
        type: string
      category:
        type: string
      notes:
        type: string
